server:
  servlet:
    context-path: /
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///sm_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: mysql123

mybatis-plus:
  type-aliases-package: com.ptt.pojo
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义